name: phpgeo CI Tasks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
          - "8.2"
          - "8.3"
          - "8.4"

    name: "phpgeo CI run - PHP ${{ matrix.php-versions }}"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-versions }}"
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: "${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('composer.json') }}"
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Lint PHP Sources
        run: composer run-script ci:lint

      - name: PHP Code Sniffer
        run: composer run-script ci:sniff

      - name: Static Analysis
        run: composer run-script ci:phpstan

      - name: Unit Tests
        run: composer run-script ci:tests
