name: Documentation

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        working-directory: documentation
        run: |
          pip install -r requirements.txt

      - name: Build Documentation
        working-directory: documentation
        run: |
          mkdocs build -d ../build/documentation

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/mjaschen/phpgeo-documentation:latest
