name: Documentation

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v9
        with:
          enable-cache: true
          cache-dependency-glob: documentation/uv.lock

      - name: Install dependencies
        working-directory: documentation
        run: uv sync --frozen

      - name: Build Documentation
        working-directory: documentation
        run: |
          uv run --frozen mkdocs build -d ../build/documentation

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/mjaschen/phpgeo-documentation:latest
